apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: clusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      
