apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterautoscaler
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    helm:
      values: |         
        autoDiscovery:
          # cloudProviders `aws`, `gce`, `azure`, `magnum` and `clusterapi` `oci-oke` are supported by auto-discovery at this time
          # AWS: Set tags as described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
          clusterName: ${EKS_CLUSTER}
        # AWS_REGION
        awsRegion: ${AWS_REGION}
        # CLOUD_PROVIDER
        cloudProvider: aws
        rbac:
          serviceAccount:
            create: true
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: ${CLUSTER_AUTOSCALER_IAM_ROLE_ARN}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
