apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterautoscaler
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.54.1
    
    helm:
      values: |         
        autoDiscovery:
          # cloudProviders `aws`, `gce`, `azure`, `magnum` and `clusterapi` `oci-oke` are supported by auto-discovery at this time
          # AWS: Set tags as described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
          clusterName: my-eks
        # AWS_REGION
        awsRegion: eu-west-2
        # CLOUD_PROVIDER
        cloudProvider: aws
        rbac:
          serviceAccount:
            create: true
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::864899862993:role/cluster-autoscaler-2026012023211083480000000c
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
